# Generated by Django 4.2.17 on 2024-12-17 08:59

import MyRestaurant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyRestaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=MyRestaurant.models.getFilename)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-hidden')),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
