# Generated by Django 4.2.17 on 2024-12-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyRestaurant', '0002_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
    ]
