# Generated by Django 4.2.17 on 2024-12-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyRestaurant', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Tasty and Yummy', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.CharField(default='Grillino', max_length=150),
        ),
    ]
