# Generated by Django 4.2.17 on 2024-12-19 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyRestaurant', '0005_alter_product_description_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Tasty and Yummy', max_length=750),
        ),
    ]
