# Generated by Django 4.2.17 on 2024-12-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyRestaurant', '0009_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookaTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
